//sliders
export const sliders = [
  {
    id: 1,
    image: "./images/slide1.jpg",
  },
  {
    id: 2,
    image: "./images/slide2.jpg",
  },
  {
    id: 3,
    image: "./images/slide3.jpg",
  },
];
//products
export const products = [
  {
    id: 1,
    title: "Bánh Crepe Phô Mai",
    category: "dessert",
    price: 15.99,
    img: "./images/cake-crepe.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 2,
    title: "Bánh Torrija",
    category: "dessert",
    price: 13.99,
    img: "./images/cake-torrija.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 3,
    title: "Bánh Hamburger ",
    category: "breakfast",
    price: 6.99,
    img: "./images/Hamburger.png",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    ingradients: ["Bột mì", "Thịt bò", "Cà chua", "Phô mai"],
    amount: 1,
  },
  {
    id: 4,
    title: "Kebab",
    category: "breakfast",
    price: 20.99,
    img: "./images/kebab.png",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    ingradients: ["Bột mì", "Thịt heo", "Rau salad", "Phô mai"],
    amount: 1,
  },
  {
    id: 5,
    title: "Pizz thập cẩm",
    category: "lunch",
    price: 22.99,
    img: "./images/pizza-mix.png",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    ingradients: ["Bột mì", "Xúc xích", "Ớt chuông", "Phô mai"],
    amount: 1,
  },
  {
    id: 6,
    title: "Pizza phô mai",
    category: "lunch",
    price: 18.99,
    img: "./images/pizza-cheese.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Trứng", "Phô mai"],
    amount: 1,
  },
  {
    id: 7,
    title: "Pizza Ô liu",
    category: "lunch",
    price: 24.99,
    img: "./images/pizza-oliu.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Nấm", "Ô liu","Xúc xích", "Phô mai"],
    amount: 1,
  },
  {
    id: 8,
    title: "Gà rán cay",
    category: "lunch",
    price: 19.99,
    img: "./images/crispy-chicken.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Gà", "Bột bắp", ],
    amount: 1,
  },
  {
    id: 9,
    title: "Bánh vani",
    category: "dessert",
    price: 19.99,
    img: "./images/cupcake-vani.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 10,
    title: "Bánh chesse vani",
    category: "dessert",
    price: 19.99,
    img: "./images/cupcake-vani.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 11,
    title: "Bánh Crepe Phô Mai",
    category: "dessert",
    price: 15.99,
    img: "./images/cake-crepe.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 12,
    title: "Bánh Sandwich Jambong",
    category: "breakfast",
    price: 13.99,
    img: "./images/item-5.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 13,
    title: "Bánh Hamburger ",
    category: "breakfast",
    price: 6.99,
    img: "./images/Hamburger.png",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    ingradients: ["Bột mì", "Thịt bò", "Cà chua", "Phô mai"],
    amount: 1,
  },
  {
    id: 14,
    title: "Bánh Hamburger Sốt tiêu",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-2.png",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    ingradients: ["Bột mì", "Thịt heo", "Rau salad", "Phô mai"],
    amount: 1,
  },
  {
    id: 15,
    title: "Pizz thập cẩm",
    category: "lunch",
    price: 22.99,
    img: "./images/pizza-mix.png",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    ingradients: ["Bột mì", "Xúc xích", "Ớt chuông", "Phô mai"],
    amount: 1,
  },
  {
    id: 16,
    title: "Pizza phô mai",
    category: "lunch",
    price: 18.99,
    img: "./images/pizza-cheese.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Trứng", "Phô mai"],
    amount: 1,
  },
  {
    id: 17,
    title: "Bánh Hamburger Cheese",
    category: "breakfast",
    price: 10.99,
    img: "./images/item-7.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Nấm", "Ô liu","Xúc xích", "Phô mai"],
    amount: 1,
  },
  {
    id: 18,
    title: "Gà rán cay",
    category: "lunch",
    price: 19.99,
    img: "./images/crispy-chicken.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Gà", "Bột bắp", ],
    amount: 1,
  },
  {
    id: 19,
    title: "Bánh vani",
    category: "dessert",
    price: 19.99,
    img: "./images/cupcake-vani.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 20,
    title: "Bánh chesse vani",
    category: "dessert",
    price: 19.99,
    img: "./images/cupcake-vani.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 21,
    title: "Bánh Crepe Phô Mai",
    category: "dessert",
    price: 15.99,
    img: "./images/cake-crepe.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 22,
    title: "Bánh Torrija",
    category: "dessert",
    price: 13.99,
    img: "./images/cake-torrija.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 23,
    title: "Bánh Hamburger ",
    category: "breakfast",
    price: 6.99,
    img: "./images/Hamburger.png",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    ingradients: ["Bột mì", "Thịt bò", "Cà chua", "Phô mai"],
    amount: 1,
  },
  {
    id: 24,
    title: "Kebab",
    category: "breakfast",
    price: 20.99,
    img: "./images/kebab.png",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    ingradients: ["Bột mì", "Thịt heo", "Rau salad", "Phô mai"],
    amount: 1,
  },
  {
    id: 25,
    title: "Pizz thập cẩm",
    category: "lunch",
    price: 22.99,
    img: "./images/pizza-mix.png",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    ingradients: ["Bột mì", "Xúc xích", "Ớt chuông", "Phô mai"],
    amount: 1,
  },
  {
    id: 26,
    title: "Pizza phô mai",
    category: "lunch",
    price: 18.99,
    img: "./images/pizza-cheese.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Trứng", "Phô mai"],
    amount: 1,
  },
  {
    id: 27,
    title: "Pizza Ô liu",
    category: "lunch",
    price: 24.99,
    img: "./images/pizza-oliu.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Nấm", "Ô liu","Xúc xích", "Phô mai"],
    amount: 1,
  },
  {
    id: 28,
    title: "Gà rán cay",
    category: "lunch",
    price: 19.99,
    img: "./images/crispy-chicken.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Gà", "Bột bắp", ],
    amount: 1,
  },
  {
    id: 29,
    title: "Bánh vani",
    category: "dessert",
    price: 19.99,
    img: "./images/cupcake-vani.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 30,
    title: "Bánh chesse vani",
    category: "dessert",
    price: 19.99,
    img: "./images/cupcake-vani.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
];

export const banners=[
  {
    id:1,
    image: "./images/banner1.jpg",
  },
  {
    id:2,
    image: "./images/banner2.png",
  },
  {
    id:3,
    image: "./images/banner3.jpg",
  }
]