//sliders
export const sliders = [
  {
    id: 1,
    image: "/images/slide1.jpg",
  },
  {
    id: 2,
    image: "/images/slide2.jpg",
  },
  {
    id: 3,
    image: "/images/slide3.jpg",
  },
];
//products
export const products = [
  {
    id: 1,
    title: "Bánh Crepe Phô Mai",
    category: "dessert",
    price: 15.99,
    img: "/images/cake-crepe.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 2,
    title: "Bánh Torrija",
    category: "dessert",
    price: 13.99,
    img: "/images/cake-torrija.png",
    desc: `Bánh cupcake dễ thương đã trở thành một hiện tượng trong giới trẻ Việt hiện nay. Những chiếc bánh cupcake ngon miệng và vô cùng đẹp mắt đã làm bao trái tim yêu ẩm thực rung động. Cupcake có rất nhiều vị phù hợp với mọi lứa tuổi: bánh cupcake socola, bánh cupcake dâu tây sữa chua, bánh cupcake trà xanh… Ta có thể mua cupcake ở bất kì cửa hàng bánh nào. Hay bây giờ có rất nhiều người tự tay làm cupcake tại nhà để làm bánh sinh nhật tặng người thân và bạn bè. Tuy nhiên có những điều thú vị về cupcake mà không phải ai cũng biết. Hãy cùng nhau tìm hiểu nhé! Đã nhiều lần thưởng thức những chiếc bánh cupcake ngon miệng, dễ thương, liệu bạn đã bao giờ tự hỏi nguồn gốc cupcake là ở đâu? Tên gọi bánh cupcake là gì?
    Cupcake đã được 200 tuổi rồi đó. Cupcake xuất hiện đầu tiên tại Mỹ vào thế kỷ 19 và nhanh chóng tạo thành một bước đột phá và phổ biến trong các gian bếp. Theo trang Food Timeline, người ta vẫn chưa tìm ra nguồn gốc thật sự của tên gọi cupcake. Họ có 2 lý giải cho tên gọi như sau: 1 là chiếc bánh truyền thông được nướng trong những chiếc cup nhỏ, 2 là những thành phần nguyên liệu của bánh được đong theo cup. `,

    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 3,
    title: "Bánh Hamburger ",
    category: "breakfast",
    price: 6.99,
    img: "/images/Hamburger.png",
    desc: `Bữa ăn sáng được coi là nguồn cung cấp năng lượng chính cho mỗi chúng ta, giúp hoạt động cả ngày. Vì vậy việc nạp đầy đủ năng lượng cho bữa ăn sáng là điều vô cùng cần thiết, đặc biệt là khi công việc bận rộn tất bật khiến chúng ta không có đủ thời gian chăm lo cho bữa sáng trọng vẹn. Hamburger được coi là sản phẩm đặc biệt với tiêu chí “ ngon-bổ-rẻ” đem đến cho khách hàng chất lượng tuyệt vời và an toàn cho sức khỏe.   Với nguồn năng lượng với hơn 1200 kcal dư sức cung cấp 120% nhu cầu năng lượng cho ngày làm việc. Hamburger được bổ sung thêm 9 loại vitamin và khoáng chất.. Bánh mì- món ăn rất quen thuộc đối với khẩu vị của mỗi người Việt và kết hợp với thịt bò đem lại hương vị đậm đà, ngon miệng. Hàm lượng dinh dưỡng trong 1 khẩu phần bánh mì bò là 760kcal.Kết hợp với rau xanh tươi nguyên từ cánh đồng tươi mát.`,
    ingradients: ["Bột mì", "Thịt bò", "Cà chua", "Phô mai"],
    amount: 1,
  },
  {
    id: 4,
    title: "Kebab",
    category: "breakfast",
    price: 20.99,
    img: "/images/kebab.png",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    ingradients: ["Bột mì", "Thịt heo", "Rau salad", "Phô mai"],
    amount: 1,
  },
  {
    id: 5,
    title: "Pizz thập cẩm",
    category: "lunch",
    price: 22.99,
    img: "/images/pizza-mix.png",
    desc: `Nguồn nguyên liệu tươi ngon được nhập chính ngạch hằng ngày đã qua kiểm định an toàn thực phẩm nên khách hàng có thể hoàn toàn yên tâm về độ tươi ngon của những chiếc bánh nơi đây.
    Bột mỳ trắng mịn cùng với phương pháp nhào bột thủ công để làm nên những chiếc đế bánh khi nướng thì nở xốp và giòn mà không hề chai cứng. Một sự kết hợp hoàn hảo giữa đế bánh và nhân bánh, Chiếc bánh bạn nhận được sẽ vẫn còn nóng hổi, viền bánh hơi cháy cạnh rất thơm và giòn tan khi đưa vào miệng. Nhân bánh đặc sánh phô mai với sốt cà chua đỏ tươi và nhiều bột xen lẫn các lát thịt, hải sản tươi thơm ngon làm nên chiếc pizza hoàn hảo và đúng phong vị nhất. Thời gian nướng và nhiệt độ nướng bánh: Thời gian nướng rất quan trọng. Chiếc pizza mang tới tận nhà cho khách cũng rất nóng hổi chứ không hề nguội. Nếu pizza để nguội thì vị thực sự của nó sẽ biến mất. Thời gian để nướng chiếc pizza rất quan trọng. Nếu không căn được thời gian nướng thì chiếc bánh có thể bị cháy, hoặc có thể đế bánh không thể giòn và cũng có thể là đế bánh chín không đều. Vậy nên nền nhiệt và thời gian rất quan trọng để quyết định cho ra một chiếc pizza đế bánh giòn rụm khi đưa vào miệng và phần nhân bánh vẫn không bị cháy. Nhiệt độ nướng tại cửa hàng pizza luôn đạt tại 250-350 độ C với thời gian 1-2 phút. Nếu tự làm ở nhà thì nướng mất khoảng 7-8 phút trong nền nhiệt 250 độ C `,
    ingradients: ["Bột mì", "Xúc xích", "Ớt chuông", "Phô mai"],
    amount: 1,
  },
  {
    id: 6,
    title: "Pizza phô mai",
    category: "lunch",
    price: 18.99,
    img: "/images/pizza-cheese.png",
    desc: `Nguồn nguyên liệu tươi ngon được nhập chính ngạch hằng ngày đã qua kiểm định an toàn thực phẩm nên khách hàng có thể hoàn toàn yên tâm về độ tươi ngon của những chiếc bánh nơi đây.
    Bột mỳ trắng mịn cùng với phương pháp nhào bột thủ công để làm nên những chiếc đế bánh khi nướng thì nở xốp và giòn mà không hề chai cứng. Một sự kết hợp hoàn hảo giữa đế bánh và nhân bánh, Chiếc bánh bạn nhận được sẽ vẫn còn nóng hổi, viền bánh hơi cháy cạnh rất thơm và giòn tan khi đưa vào miệng. Nhân bánh đặc sánh phô mai với sốt cà chua đỏ tươi và nhiều bột xen lẫn các lát thịt, hải sản tươi thơm ngon làm nên chiếc pizza hoàn hảo và đúng phong vị nhất. Thời gian nướng và nhiệt độ nướng bánh: Thời gian nướng rất quan trọng. Chiếc pizza mang tới tận nhà cho khách cũng rất nóng hổi chứ không hề nguội. Nếu pizza để nguội thì vị thực sự của nó sẽ biến mất. Thời gian để nướng chiếc pizza rất quan trọng. Nếu không căn được thời gian nướng thì chiếc bánh có thể bị cháy, hoặc có thể đế bánh không thể giòn và cũng có thể là đế bánh chín không đều. Vậy nên nền nhiệt và thời gian rất quan trọng để quyết định cho ra một chiếc pizza đế bánh giòn rụm khi đưa vào miệng và phần nhân bánh vẫn không bị cháy. Nhiệt độ nướng tại cửa hàng pizza luôn đạt tại 250-350 độ C với thời gian 1-2 phút. Nếu tự làm ở nhà thì nướng mất khoảng 7-8 phút trong nền nhiệt 250 độ C `,
    ingradients: ["Bột mì", "Trứng", "Phô mai"],
    amount: 1,
  },
  {
    id: 7,
    title: "Pizza Ô liu",
    category: "lunch",
    price: 24.99,
    img: "/images/pizza-oliu.png",
    desc: `Nguồn nguyên liệu tươi ngon được nhập chính ngạch hằng ngày đã qua kiểm định an toàn thực phẩm nên khách hàng có thể hoàn toàn yên tâm về độ tươi ngon của những chiếc bánh nơi đây.
    Bột mỳ trắng mịn cùng với phương pháp nhào bột thủ công để làm nên những chiếc đế bánh khi nướng thì nở xốp và giòn mà không hề chai cứng. Một sự kết hợp hoàn hảo giữa đế bánh và nhân bánh, Chiếc bánh bạn nhận được sẽ vẫn còn nóng hổi, viền bánh hơi cháy cạnh rất thơm và giòn tan khi đưa vào miệng. Nhân bánh đặc sánh phô mai với sốt cà chua đỏ tươi và nhiều bột xen lẫn các lát thịt, hải sản tươi thơm ngon làm nên chiếc pizza hoàn hảo và đúng phong vị nhất. Thời gian nướng và nhiệt độ nướng bánh: Thời gian nướng rất quan trọng. Chiếc pizza mang tới tận nhà cho khách cũng rất nóng hổi chứ không hề nguội. Nếu pizza để nguội thì vị thực sự của nó sẽ biến mất. Thời gian để nướng chiếc pizza rất quan trọng. Nếu không căn được thời gian nướng thì chiếc bánh có thể bị cháy, hoặc có thể đế bánh không thể giòn và cũng có thể là đế bánh chín không đều. Vậy nên nền nhiệt và thời gian rất quan trọng để quyết định cho ra một chiếc pizza đế bánh giòn rụm khi đưa vào miệng và phần nhân bánh vẫn không bị cháy. Nhiệt độ nướng tại cửa hàng pizza luôn đạt tại 250-350 độ C với thời gian 1-2 phút. Nếu tự làm ở nhà thì nướng mất khoảng 7-8 phút trong nền nhiệt 250 độ C `,
    ingradients: ["Bột mì", "Nấm", "Ô liu", "Xúc xích", "Phô mai"],
    amount: 1,
  },
  {
    id: 8,
    title: "Gà rán cay",
    category: "lunch",
    price: 19.99,
    img: "/images/crispy-chicken.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Gà", "Bột bắp"],
    amount: 1,
  },
  {
    id: 9,
    title: "Bánh vani",
    category: "dessert",
    price: 19.99,
    img: "/images/cupcake-vani.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 10,
    title: "Bánh Chocolate Cream",
    category: "dessert",
    price: 19.99,
    img: "/images/cupcake-chocolate.png",
    desc: `Bánh cupcake dễ thương đã trở thành một hiện tượng trong giới trẻ Việt hiện nay. Những chiếc bánh cupcake ngon miệng và vô cùng đẹp mắt đã làm bao trái tim yêu ẩm thực rung động. Cupcake có rất nhiều vị phù hợp với mọi lứa tuổi: bánh cupcake socola, bánh cupcake dâu tây sữa chua, bánh cupcake trà xanh… Ta có thể mua cupcake ở bất kì cửa hàng bánh nào. Hay bây giờ có rất nhiều người tự tay làm cupcake tại nhà để làm bánh sinh nhật tặng người thân và bạn bè. Tuy nhiên có những điều thú vị về cupcake mà không phải ai cũng biết. Hãy cùng nhau tìm hiểu nhé!Hoa sinh nhật 2 trong một với cupcake – một chiếc happy birthday cake tuyệt vời để tặng quà sinh nhật cho bạn gái nhỉ? Một chút sáng tạo, cộng với sự giúp đỡ của… bánh quế và kem phủ, bạn đã có ngay cupcake giày cao gót làm quà sinh nhật bạn gái. Con gái không thể chê một món quà sinh nhật tâm lý và tuyệt vời thế này từ bạn trai của mình đâu.
    Chắc hẳn sau những mẫu bánh GATO giới thiệu, bạn đã chọn được một món quà sinh nhật bạn gái, quà tặng sinh nhật gia đình hay bé yêu rồi! Chúc các bạn tìm được một món quà sinh nhật ý nghĩa cho những người quan trọng nhé.Được cái ngắm bánh nở phồng trong lò nướng cũng như ngửi mùi bơ thơm phức lại chẳng cầm lòng được hi hi :P Thế là có hai ổ bánh ra đời trong hai ngày cuối tuần. Trời, nhiều quá ha. Không sao, ăn cùng người thương và bạn bè thân thiết mà, có măm hết cả đâu mà lo, „Eo“ nhỉ! ;) (tự nhủ với cái Eo như thế. Kiểu này lại sắp có cái eo bánh mỳ rồi đây, bởi làm bánh  ngọt thì không thể thiếu trứng và bơ.`,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 11,
    title: "Gà rán hàn quốc",
    category: "dessert",
    price: 15.99,
    img: "/images/Gà rán hàn quốc.jpeg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 12,
    title: "Bánh Sandwich Jambong",
    category: "breakfast",
    price: 13.99,
    img: "/images/item-5.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 13,
    title: "Bánh Taco ",
    category: "breakfast",
    price: 6.99,
    img: "/images/Bánh Taco.png",
    desc: `Bữa ăn sáng được coi là nguồn cung cấp năng lượng chính cho mỗi chúng ta, giúp hoạt động cả ngày. Vì vậy việc nạp đầy đủ năng lượng cho bữa ăn sáng là điều vô cùng cần thiết, đặc biệt là khi công việc bận rộn tất bật khiến chúng ta không có đủ thời gian chăm lo cho bữa sáng trọng vẹn. Hamburger được coi là sản phẩm đặc biệt với tiêu chí “ ngon-bổ-rẻ” đem đến cho khách hàng chất lượng tuyệt vời và an toàn cho sức khỏe.   Với nguồn năng lượng với hơn 1200 kcal dư sức cung cấp 120% nhu cầu năng lượng cho ngày làm việc. Hamburger được bổ sung thêm 9 loại vitamin và khoáng chất.. Bánh mì- món ăn rất quen thuộc đối với khẩu vị của mỗi người Việt và kết hợp với thịt bò đem lại hương vị đậm đà, ngon miệng. Hàm lượng dinh dưỡng trong 1 khẩu phần bánh mì bò là 760kcal.Kết hợp với rau xanh tươi nguyên từ cánh đồng tươi mát.
     `,
    ingradients: ["Bột mì", "Thịt bò", "Cà chua", "Phô mai"],
    amount: 1,
  },
  {
    id: 14,
    title: "Bánh Hamburger Sốt tiêu",
    category: "breakfast",
    price: 20.99,
    img: "/images/item-2.png",
    desc: `Bữa ăn sáng được coi là nguồn cung cấp năng lượng chính cho mỗi chúng ta, giúp hoạt động cả ngày. Vì vậy việc nạp đầy đủ năng lượng cho bữa ăn sáng là điều vô cùng cần thiết, đặc biệt là khi công việc bận rộn tất bật khiến chúng ta không có đủ thời gian chăm lo cho bữa sáng trọng vẹn. Hamburger được coi là sản phẩm đặc biệt với tiêu chí “ ngon-bổ-rẻ” đem đến cho khách hàng chất lượng tuyệt vời và an toàn cho sức khỏe.   Với nguồn năng lượng với hơn 1200 kcal dư sức cung cấp 120% nhu cầu năng lượng cho ngày làm việc. Hamburger được bổ sung thêm 9 loại vitamin và khoáng chất.. Bánh mì- món ăn rất quen thuộc đối với khẩu vị của mỗi người Việt và kết hợp với thịt bò đem lại hương vị đậm đà, ngon miệng. Hàm lượng dinh dưỡng trong 1 khẩu phần bánh mì bò là 760kcal.Kết hợp với rau xanh tươi nguyên từ cánh đồng tươi mát. `,
    ingradients: ["Bột mì", "Thịt heo", "Rau salad", "Phô mai"],
    amount: 1,
  },
  {
    id: 15,
    title: "Xúc xích nướng",
    category: "lunch",
    price: 22.99,
    img: "/images/Xúc xích nướng.jpg",
    desc: `Nguồn nguyên liệu tươi ngon được nhập chính ngạch hằng ngày đã qua kiểm định an toàn thực phẩm nên khách hàng có thể hoàn toàn yên tâm về độ tươi ngon của những chiếc bánh nơi đây.
    Bột mỳ trắng mịn cùng với phương pháp nhào bột thủ công để làm nên những chiếc đế bánh khi nướng thì nở xốp và giòn mà không hề chai cứng. Một sự kết hợp hoàn hảo giữa đế bánh và nhân bánh, Chiếc bánh bạn nhận được sẽ vẫn còn nóng hổi, viền bánh hơi cháy cạnh rất thơm và giòn tan khi đưa vào miệng. Nhân bánh đặc sánh phô mai với sốt cà chua đỏ tươi và nhiều bột xen lẫn các lát thịt, hải sản tươi thơm ngon làm nên chiếc pizza hoàn hảo và đúng phong vị nhất. Thời gian nướng và nhiệt độ nướng bánh: Thời gian nướng rất quan trọng. Chiếc pizza mang tới tận nhà cho khách cũng rất nóng hổi chứ không hề nguội. Nếu pizza để nguội thì vị thực sự của nó sẽ biến mất. Thời gian để nướng chiếc pizza rất quan trọng. Nếu không căn được thời gian nướng thì chiếc bánh có thể bị cháy, hoặc có thể đế bánh không thể giòn và cũng có thể là đế bánh chín không đều. Vậy nên nền nhiệt và thời gian rất quan trọng để quyết định cho ra một chiếc pizza đế bánh giòn rụm khi đưa vào miệng và phần nhân bánh vẫn không bị cháy. Nhiệt độ nướng tại cửa hàng pizza luôn đạt tại 250-350 độ C với thời gian 1-2 phút. Nếu tự làm ở nhà thì nướng mất khoảng 7-8 phút trong nền nhiệt 250 độ C  `,
    ingradients: ["Bột mì", "Xúc xích", "Ớt chuông", "Phô mai"],
    amount: 1,
  },
  {
    id: 16,
    title: "Khoai tây chiên",
    category: "lunch",
    price: 18.99,
    img: "/images/Khoai tây chiên.jpg",
    desc: `Nguồn nguyên liệu tươi ngon được nhập chính ngạch hằng ngày đã qua kiểm định an toàn thực phẩm nên khách hàng có thể hoàn toàn yên tâm về độ tươi ngon của những chiếc bánh nơi đây.
    Bột mỳ trắng mịn cùng với phương pháp nhào bột thủ công để làm nên những chiếc đế bánh khi nướng thì nở xốp và giòn mà không hề chai cứng. Một sự kết hợp hoàn hảo giữa đế bánh và nhân bánh, Chiếc bánh bạn nhận được sẽ vẫn còn nóng hổi, viền bánh hơi cháy cạnh rất thơm và giòn tan khi đưa vào miệng. Nhân bánh đặc sánh phô mai với sốt cà chua đỏ tươi và nhiều bột xen lẫn các lát thịt, hải sản tươi thơm ngon làm nên chiếc pizza hoàn hảo và đúng phong vị nhất. Thời gian nướng và nhiệt độ nướng bánh: Thời gian nướng rất quan trọng. Chiếc pizza mang tới tận nhà cho khách cũng rất nóng hổi chứ không hề nguội. Nếu pizza để nguội thì vị thực sự của nó sẽ biến mất. Thời gian để nướng chiếc pizza rất quan trọng. Nếu không căn được thời gian nướng thì chiếc bánh có thể bị cháy, hoặc có thể đế bánh không thể giòn và cũng có thể là đế bánh chín không đều. Vậy nên nền nhiệt và thời gian rất quan trọng để quyết định cho ra một chiếc pizza đế bánh giòn rụm khi đưa vào miệng và phần nhân bánh vẫn không bị cháy. Nhiệt độ nướng tại cửa hàng pizza luôn đạt tại 250-350 độ C với thời gian 1-2 phút. Nếu tự làm ở nhà thì nướng mất khoảng 7-8 phút trong nền nhiệt 250 độ C `,
    ingradients: ["Bột mì", "Trứng", "Phô mai"],
    amount: 1,
  },
  {
    id: 17,
    title: "Bánh Hamburger Cheese Trứng jambong",
    category: "breakfast",
    price: 10.99,
    img: "/images/item-7.png",
    desc: `Bữa ăn sáng được coi là nguồn cung cấp năng lượng chính cho mỗi chúng ta, giúp hoạt động cả ngày. Vì vậy việc nạp đầy đủ năng lượng cho bữa ăn sáng là điều vô cùng cần thiết, đặc biệt là khi công việc bận rộn tất bật khiến chúng ta không có đủ thời gian chăm lo cho bữa sáng trọng vẹn. Hamburger được coi là sản phẩm đặc biệt với tiêu chí “ ngon-bổ-rẻ” đem đến cho khách hàng chất lượng tuyệt vời và an toàn cho sức khỏe.   Với nguồn năng lượng với hơn 1200 kcal dư sức cung cấp 120% nhu cầu năng lượng cho ngày làm việc. Hamburger được bổ sung thêm 9 loại vitamin và khoáng chất.. Bánh mì- món ăn rất quen thuộc đối với khẩu vị của mỗi người Việt và kết hợp với thịt bò đem lại hương vị đậm đà, ngon miệng. Hàm lượng dinh dưỡng trong 1 khẩu phần bánh mì bò là 760kcal.Kết hợp với rau xanh tươi nguyên từ cánh đồng tươi mát.`,
    ingradients: ["Bột mì", "Nấm", "Ô liu", "Xúc xích", "Phô mai"],
    amount: 1,
  },
  {
    id: 18,
    title: "Gà rán cay",
    category: "lunch",
    price: 19.99,
    img: "/images/crispy-chicken.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Gà", "Bột bắp"],
    amount: 1,
  },
  {
    id: 19,
    title: "Bánh Kem Dâu",
    category: "dessert",
    price: 19.99,
    img: "/images/cakecup-strawberry.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 20,
    title: "Bánh Kem Bạc Hà",
    category: "dessert",
    price: 19.99,
    img: "/images/cakecup-mint.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 21,
    title: "SandWich thịt nguội",
    category: "dessert",
    price: 15.99,
    img: "/images/sandwich-origin.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 22,
    title: "Bánh Torrija",
    category: "dessert",
    price: 13.99,
    img: "/images/cake-torrija.png",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingradients: ["Bột mì", "Sữa", "Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 23,
    title: "Bánh Donut",
    category: "breakfast",
    price: 6.99,
    img: "/images/Bánh Donut.jpg",
    desc: `Bữa ăn sáng được coi là nguồn cung cấp năng lượng chính cho mỗi chúng ta, giúp hoạt động cả ngày. Vì vậy việc nạp đầy đủ năng lượng cho bữa ăn sáng là điều vô cùng cần thiết, đặc biệt là khi công việc bận rộn tất bật khiến chúng ta không có đủ thời gian chăm lo cho bữa sáng trọng vẹn. Hamburger được coi là sản phẩm đặc biệt với tiêu chí “ ngon-bổ-rẻ” đem đến cho khách hàng chất lượng tuyệt vời và an toàn cho sức khỏe.   Với nguồn năng lượng với hơn 1200 kcal dư sức cung cấp 120% nhu cầu năng lượng cho ngày làm việc. Hamburger được bổ sung thêm 9 loại vitamin và khoáng chất.. Bánh mì- món ăn rất quen thuộc đối với khẩu vị của mỗi người Việt và kết hợp với thịt bò đem lại hương vị đậm đà, ngon miệng. Hàm lượng dinh dưỡng trong 1 khẩu phần bánh mì bò là 760kcal.Kết hợp với rau xanh tươi nguyên từ cánh đồng tươi mát.`,
    ingradients: ["Bột mì","Kem", "Phô mai"],
    amount: 1,
  },
  {
    id: 24,
    title: "Kebab",
    category: "breakfast",
    price: 20.99,
    img: "/images/kebab.png",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    ingradients: ["Bột mì", "Thịt heo", "Rau salad", "Phô mai"],
    amount: 1,
  },
  {
    id: 25,
    title: "Mỳ ý sốt bò bằm ",
    category: "lunch",
    price: 22.99,
    img: "/images/sapaghetti.png",
    desc: `Nguồn nguyên liệu tươi ngon được nhập chính ngạch hằng ngày đã qua kiểm định an toàn thực phẩm nên khách hàng có thể hoàn toàn yên tâm về độ tươi ngon của những chiếc bánh nơi đây.
    Bột mỳ trắng mịn cùng với phương pháp nhào bột thủ công để làm nên những sợi mì thì nở xốp và giòn mà không hề chai cứng. Một sự kết hợp hoàn hảo giữa đế bánh và nhân bánh, Chiếc bánh bạn nhận được sẽ vẫn còn nóng hổi, viền bánh hơi cháy cạnh rất thơm và giòn tan khi đưa vào miệng. Nhân bánh đặc sánh phô mai với sốt cà chua đỏ tươi và nhiều bột xen lẫn các lát thịt, hải sản tươi thơm ngon làm nên chiếc pizza hoàn hảo và đúng phong vị nhất. Thời gian nướng và nhiệt độ nướng bánh: Thời gian nướng rất quan trọng. Chiếc pizza mang tới tận nhà cho khách cũng rất nóng hổi chứ không hề nguội. Nếu pizza để nguội thì vị thực sự của nó sẽ biến mất. Thời gian để nướng chiếc pizza rất quan trọng. Nếu không căn được thời gian nướng thì chiếc bánh có thể bị cháy, hoặc có thể đế bánh không thể giòn và cũng có thể là đế bánh chín không đều. Vậy nên nền nhiệt và thời gian rất quan trọng để quyết định cho ra một chiếc pizza đế bánh giòn rụm khi đưa vào miệng và phần nhân bánh vẫn không bị cháy. Nhiệt độ nướng tại cửa hàng pizza luôn đạt tại 250-350 độ C với thời gian 1-2 phút. Nếu tự làm ở nhà thì nướng mất khoảng 7-8 phút trong nền nhiệt 250 độ C  `,
    ingradients: ["Bột mì", "Xúc xích", "Ớt chuông", "Phô mai"],
    amount: 1,
  },
  {
    id: 26,
    title: "Pizza xúc xích",
    category: "lunch",
    price: 18.99,
    img: "/images/Pizza xúc xích.jpg",
    desc: `Nguồn nguyên liệu tươi ngon được nhập chính ngạch hằng ngày đã qua kiểm định an toàn thực phẩm nên khách hàng có thể hoàn toàn yên tâm về độ tươi ngon của những chiếc bánh nơi đây.
    Bột mỳ trắng mịn cùng với phương pháp nhào bột thủ công để làm nên những chiếc đế bánh khi nướng thì nở xốp và giòn mà không hề chai cứng. Một sự kết hợp hoàn hảo giữa đế bánh và nhân bánh, Chiếc bánh bạn nhận được sẽ vẫn còn nóng hổi, viền bánh hơi cháy cạnh rất thơm và giòn tan khi đưa vào miệng. Nhân bánh đặc sánh phô mai với sốt cà chua đỏ tươi và nhiều bột xen lẫn các lát thịt, hải sản tươi thơm ngon làm nên chiếc pizza hoàn hảo và đúng phong vị nhất. Thời gian nướng và nhiệt độ nướng bánh: Thời gian nướng rất quan trọng. Chiếc pizza mang tới tận nhà cho khách cũng rất nóng hổi chứ không hề nguội. Nếu pizza để nguội thì vị thực sự của nó sẽ biến mất. Thời gian để nướng chiếc pizza rất quan trọng. Nếu không căn được thời gian nướng thì chiếc bánh có thể bị cháy, hoặc có thể đế bánh không thể giòn và cũng có thể là đế bánh chín không đều. Vậy nên nền nhiệt và thời gian rất quan trọng để quyết định cho ra một chiếc pizza đế bánh giòn rụm khi đưa vào miệng và phần nhân bánh vẫn không bị cháy. Nhiệt độ nướng tại cửa hàng pizza luôn đạt tại 250-350 độ C với thời gian 1-2 phút. Nếu tự làm ở nhà thì nướng mất khoảng 7-8 phút trong nền nhiệt 250 độ C `,
    ingradients: ["Bột mì", "Trứng", "Phô mai"],
    amount: 1,
  },
  {
    id: 27,
    title: "Pizza sầu riêng",
    category: "lunch",
    price: 24.99,
    img: "/images/Pizza sầu riêng.png",
    desc: `Nguồn nguyên liệu tươi ngon được nhập chính ngạch hằng ngày đã qua kiểm định an toàn thực phẩm nên khách hàng có thể hoàn toàn yên tâm về độ tươi ngon của những chiếc bánh nơi đây.
    Bột mỳ trắng mịn cùng với phương pháp nhào bột thủ công để làm nên những chiếc đế bánh khi nướng thì nở xốp và giòn mà không hề chai cứng. Một sự kết hợp hoàn hảo giữa đế bánh và nhân bánh, Chiếc bánh bạn nhận được sẽ vẫn còn nóng hổi, viền bánh hơi cháy cạnh rất thơm và giòn tan khi đưa vào miệng. Nhân bánh đặc sánh phô mai với sốt cà chua đỏ tươi và nhiều bột xen lẫn các lát thịt, hải sản tươi thơm ngon làm nên chiếc pizza hoàn hảo và đúng phong vị nhất. Thời gian nướng và nhiệt độ nướng bánh: Thời gian nướng rất quan trọng. Chiếc pizza mang tới tận nhà cho khách cũng rất nóng hổi chứ không hề nguội. Nếu pizza để nguội thì vị thực sự của nó sẽ biến mất. Thời gian để nướng chiếc pizza rất quan trọng. Nếu không căn được thời gian nướng thì chiếc bánh có thể bị cháy, hoặc có thể đế bánh không thể giòn và cũng có thể là đế bánh chín không đều. Vậy nên nền nhiệt và thời gian rất quan trọng để quyết định cho ra một chiếc pizza đế bánh giòn rụm khi đưa vào miệng và phần nhân bánh vẫn không bị cháy. Nhiệt độ nướng tại cửa hàng pizza luôn đạt tại 250-350 độ C với thời gian 1-2 phút. Nếu tự làm ở nhà thì nướng mất khoảng 7-8 phút trong nền nhiệt 250 độ C `,
    ingradients: ["Bột mì", "Sầu riêng", "Phô mai"],
    amount: 1,
  },
  {
    id: 28,
    title: "Gà rán sốt cay",
    category: "lunch",
    price: 19.99,
    img: "/images/Gà rán sốt cay.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Bột mì", "Gà", "Bột bắp"],
    amount: 1,
  },
  {
    id: 29,
    title: "Cơm Gà Nướng Tiêu",
    category: "lunch",
    price: 19.99,
    img: "/images/chicken-grill.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["Gạo", "Gà", "Salad", "Tiêu"],
    amount: 1,
  },
  {
    id: 30,
    title: "Hotdog",
    category: "lunch",
    price: 19.99,
    img: "/images/Hotdog.png",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    ingradients: ["bột mì", "Thịt heo", "Phô mai"],
    amount: 1,
  },
];

export const banners = [
  {
    id: 1,
    image: "/images/banner1.jpg",
  },
  {
    id: 2,
    image: "/images/banner2.png",
  },
  {
    id: 3,
    image: "/images/banner3.jpg",
  },
];

export const navLinks = [
  {
    id: 1,
    path: "/",
    text: "Trang chủ",
  },
  {
    id: 2,
    path: "/about",
    text: "Giới thiệu",
  },
  {
    id: 3,
    path: "/foods",
    text: "Sản phẩm",
  },
  {
    id: 4,
    path: "/contact",
    text: "Liên hệ",
  },
];

export const about = [
  {
    id: 1,
    img: "/images/about3.jpg",
    heading: "Gần Gũi",
    text: "Chúng tôi có niềm tin vào tính gần gũi mà thanh liêm, nền tảng vững chắc cho một cuộc sống trung thực, bình dân và thành thật với bản thân.",
  },
  {
    id: 2,
    img: "/images/about4.jpg",
    heading: "Vui Vẻ",
    text: "Chúng tôi dễ gần, đáng yêu và tràn đầy năng lượng, luôn mang đến niềm vui cho những người xung quanh.",
  },
  {
    id: 2,
    img: "/images/about5.jpg",
    heading: "Đồng Lòng",
    text: "Chúng tôi thích tận hưởng thời gian bên nhau giống như tận hưởng việc mua sắm trực tuyến với người thân và bạn bè - làm những việc yêu thích cùng nhau như một đại gia đình lớn.",
  },
];
